Y0ungZ/algorithm-study

송유선/5주차/10994_별찍기19.cpp, 송유선/5주차/12904_A와B.cpp, 송유선/5주차/12919_A와B2.cpp, 송유선/5주차/16719_ZOAC.cpp, 송유선/5주차/2442_별찍기5.cpp
=> [유선] 5주차 과제

황상진/5주차/12919_A와B2.cpp, 황상진/5주차/16719_ZOAC.cpp
=> [상진] 5주차 과제

노영주/6주차/12015_가장긴증가하는부분수열2.js, 노영주/6주차/16234_인구이동.js
- 오답 1(틀렸습니다) : 열린 국경선을 체크하는 배열 방문처리를 이상하게 함.
- 오답 2(시간초과) : 80%부근에서 시간초과 발생해서 이중 for문을 줄이게 수정
=> [영주] 6주차 과제

송유선/6주차/1072_게임.cpp, 송유선/6주차/11053_가장긴증가하는부분수열.cpp, 송유선/6주차/12015_가장긴증가하는부분수열2.cpp, 송유선/6주차/16234_인구이동.cpp, 송유선/6주차/2512_예산.cpp
=> [유선] 6주차 과제

윤호선/7주차/1300_K번째수.cpp, 윤호선/7주차/19539_사과나무.cpp, 윤호선/7주차/2015_수들의_합4.cpp, 윤호선/7주차/2023_신기한_소수.cpp
=> [호선] 7주차 과제

노영주/7주차/1300_K번째수.js, 노영주/7주차/19539_사과나무.js, 노영주/7주차/2015_수들의합4.js, 노영주/7주차/2023_신기한소수.js
* [[2023-02-19 기준] node.js 메모리 제한으로 해결한 사람 없음.](https://www.acmicpc.net/status?problem_id=2023&user_id=&language_id=17&result_id=-1&from_problem=1)
* 1<=N<=8 까지 정답 출력되는 것은 확인했습니다.
=> [영주] 7주차 과제

황상진/6주차/12015_가장긴증가하는부분수열2.cpp, 황상진/6주차/16234_인구이동.cpp
=> [상진] 6주차 과제

황상진/7주차/1300.cpp, 황상진/7주차/19539.cpp, 황상진/7주차/2015.cpp, 황상진/7주차/2023.cpp
=> [상진] 7주차 과제

노영주/8주차/1263_시간관리.js, 노영주/8주차/16120_PPAP.js, 노영주/8주차/20159_동작그만밑장빼기냐.js
=> [영주] 8주차 과제

윤호선/8주차/1263_시간관리.cpp, 윤호선/8주차/16120_PPAP.cpp, 윤호선/8주차/20159_동작그만.밑장빼기냐.cpp
=> [호선] 8주차 과제

노영주/9주차/2098,10971_외판원순회.js, 노영주/9주차/2573_빙산.js
=> [영주] 9주차 과제

윤호선/9주차/10971_외판원순회2.cpp, 윤호선/9주차/2573_빙산.cpp
=> [호선] 9주차 과제

송유선/7주차/1300_K번째수.cpp, 송유선/7주차/19539_사과나무.cpp, 송유선/7주차/2015_수들의합4.cpp, 송유선/7주차/2023_신기한소수.cpp
=> [유선] 7주차 과제

노영주/10주차/1194_달이차오른다가자.js, 노영주/10주차/17406_배열돌리기4.js
=> [영주] 10주차 과제

윤호선/10주차/1194_달이차오른다,가자.cpp, 윤호선/10주차/17406_배열돌리기4.cpp
=> [호선] 10주차 과제

황상진/9주차/10971_외판원_순회_2.cpp, 황상진/9주차/2573_빙산_.cpp
=> [상진] 9주차 과제

윤호선/11주차/10799_쇠막대기.cpp, 윤호선/11주차/2343_기타레슨.cpp
=> [호선] 11주차 과제

송유선/10주차/17406_배열돌리기4.cpp
=> [유선] 10주차 과제 

송유선/11주차/10799_쇠막대기.cpp, 송유선/11주차/2343_기타레슨.cpp
=> [유선] 11주차 과제

노영주/12주차/13335_트럭.js, 노영주/12주차/15684_사다리조작.js
=> [영주] 12주차 과제

노영주/13주차/1446_지름길.js, 노영주/13주차/1525_퍼즐.js
=> [영주] 13주차 과제

노영주/14주차/1504_특정한최단경로.js, 노영주/14주차/2644_촌수계산.js
=> [영주] 14주차 과제

윤호선/14주차/1504_특정한_최단_경로.cpp, 윤호선/14주차/2644_촌수계산.cpp
=> [호선] 14주차 과제

노영주/15주차/10844_쉬운계단수.js, 노영주/15주차/2293_동전1.js
- [[2023-04-17 기준] node.js 메모리 제한으로 해결한 사람 없음.](https://www.acmicpc.net/status?problem_id=2293&user_id=&language_id=17&result_id=-1&from_problem=1)
- 생각한 반례는 모두 정답 출력 확인했습니다.
=> [영주] 15주차 과제

송유선/13주차/1446_지름길.cpp
=> [유선] 13주차 과제

노영주/16주차/1062_가르침.js, 노영주/16주차/이모티콘할인행사.js
=> [영주] 16주차 과제 

송유선/16주차/1062_가르침.cpp, 송유선/16주차/이모티콘 할인행사.cpp
=> [유선] 16주차 과제

윤호선/15주차/10844_쉬운_계단수.cpp, 윤호선/15주차/2293_동전1.cpp
=> [호선] 15주차 과제

윤호선/16주차/1062_가르침.cpp, 윤호선/16주차/프로그래머스_이모티콘할인행사.cpp
=> [호선] 16주차 과제

윤호선/17주차/3055_탈출.cpp, 윤호선/17주차/프로그래머스_택배배달과_수거하기.cpp
=> [호선] 17주차 과제

노영주/17주차/3055_탈출.js, 노영주/17주차/택배배달과수거하기.js
=> [영주] 17주차 과제

윤호선/18주차/20058_마법사상어와_파이어스톰.cpp, 윤호선/18주차/뉴스_클러스터링.cpp
=> [호선] 18주차 과제

윤호선/19주차/1912_연속합.cpp
=> [호선] 19주차 과제

윤호선/21주차/1005_ACM Craft.cpp, 윤호선/21주차/행렬_테두리_회전하기.cpp
=> [호선] 21주차 과제

윤호선/22주차/보석쇼핑.cpp
=> [호선] 22주차 과제

노영주/20주차/2470_두용액.js, 노영주/20주차/2866_문자열잘라내기.js
=> [영주] 20주차 과제

윤호선/23주차/2146_다리만들기.cpp, 윤호선/23주차/2668_숫자고르기.cpp
=> [호선] 23주차 과제

윤호선/24주차/1325_효율적인_해킹.cpp, 윤호선/24주차/미로_탈출_명령어.cpp
=> [호선] 24주차 과제

윤호선/25주차/3085_사탕게임.cpp, 윤호선/25주차/다단계_칫솔_판매.cpp
=> [호선] 25주차 과제

윤호선/26주차/2981_검문.cpp
=> [호선] 26주차 과제

송유선/20주차/2470_두용액.cpp
=> [유선] 20주차 과제

송유선/26주차/2981_검문.cpp
=> [유선] 26주차 과제

노영주/26주차/2981_검문.js
=> [영주] 26주차 과제

송유선/27주차/1976_여행가자.cpp, 송유선/27주차/5052_전화번호목록.cpp
=> [유선] 27주차 과제

노영주/27주차/1976_여행가자.js, 노영주/27주차/5052_전화번호목록.js
=> [영주] 27주차 과제 

윤호선/28주차/10942_펠린드롬.cpp, 윤호선/28주차/1939_중량제한.cpp
=> [호선] 28주차 과제

노영주/28주차/10942_팰린드롬.js, 노영주/28주차/1939_중량제한.js
=> [영주] 28주차 과제

노영주/30주차/2504_괄호의값.js, 노영주/30주차/2565_전깃줄.js
=> [영주] 30주차 과제

노영주/31주차/1715_카드정렬하기.js, 노영주/31주차/2468_안전영역.js
=> [영주] 31주차 과제

노영주/32주차/과제진행하기.js, 노영주/32주차/요격시스템.js
=> [영주] 32주차 과제

윤호선/29주차/14890_경사로.cpp, 윤호선/29주차/5639_이진검색트리.cpp
=> [호선] 29주차 과제

윤호선/30주차/2504_괄호의 값.cpp, 윤호선/30주차/2565_전깃줄.cpp
=> [호선] 30주차 과제

윤호선/31주차/1715_카드정렬하기.cpp, 윤호선/31주차/2468_안전영역.cpp
=> [호선] 31주차 과제

윤호선/32주차/과제진행하기.cpp, 윤호선/32주차/요격시스템.cpp
=> [호선] 32주차 과제

윤호선/33주차/테이블_해시_함수.cpp, 윤호선/33주차/혼자서_하는_틱택토.cpp
=> [호선] 33주차 과제

노영주/33주차/테이블해시함수.js, 노영주/33주차/혼자서하는틱택토.js
=> [영주] 33주차 과제

윤호선/34주차/베스트앨범.cpp, 윤호선/34주차/숫자게임.cpp
=> [호선] 34주차 과제

노영주/34주차/베스트앨범.js, 노영주/34주차/숫자게임.js
=> [영주] 34주차 과제

노영주/35주차/야근지수.js, 노영주/35주차/최고의집합.js
=> [영주] 35주차 과제

노영주/36주차/섬연결하기.js, 노영주/36주차/징검다리건너기.js
=> [영주] 36주차 과제

노영주/37주차/경주로건설.js, 노영주/37주차/단속카메라.js
=> [영주] 37주차 과제

노영주/38주차/기지국설치.js
=> [영주] 38주차 과제

윤호선/35주차/야근 지수.cpp, 윤호선/35주차/최고의 집합.cpp
=> [호선] 35주차 과제

윤호선/36주차/섬 연결하기.cpp, 윤호선/36주차/징검다리 건너기.cpp
=> [호선] 36주차 과제

윤호선/37주차/경주로 건설.cpp, 윤호선/37주차/단속카메라.cpp
=> [호선] 37주차 과제

노영주/39주차/외벽점검.js, 노영주/39주차/표현가능한이진트리.js
=> [영주] 39주차 과제

노영주/40주차/방금그곡.js
=> [영주] 40주차 과제 

노영주/41주차/1202_보석도둑.js, 노영주/41주차/[1차]셔틀버스.js
=> [영주] 41주차 과제

노영주/42주차/n2배열자르기.js, 노영주/42주차/자물쇠와열쇠.js
=> [영주] 42주차 과제

윤호선/40주차/방금그곡.cpp
=> [호선] 40주차 과제

윤호선/41주차/JewelThief.java, 윤호선/41주차/ShuttleBus.java
=> [호선] 41주차 과제

윤호선/42주차/LockAndKey.java, 윤호선/42주차/n^2 배열 자르기.java
=> [호선] 42주차 과제

윤호선/43주차/ACMC.java, 윤호선/43주차/LineUp.java, 윤호선/43주차/WhatDoesTheFoxSay.java
=> [호선] 43주차 과제

노영주/43주차/1005_ACMCraft.js, 노영주/43주차/2252_줄세우기.js, 노영주/43주차/9536_여우는어떻게울지.js
=> [영주] 43주차 과제

노영주/44주차/11559_PuyoPuyo.js, 노영주/44주차/15922_아우으우아으이야.js
=> [영주] 44주차 과제

노영주/45주차/가장많이받은선물.js, 노영주/45주차/도넛과막대그래프.js
=> [영주] 45주차 과제

윤호선/45주차/가장많이받은선물.java, 윤호선/45주차/도넛과막대그래프.java
=> [호선] 45주차 과제

노영주/46주차/붕대감기.js, 노영주/46주차/주사위고르기.js
=> [영주] 46주차 과제

노영주/47주차/n+1카드게임.js, 노영주/47주차/석유시추.js
=> [영주] 47주차 과제
